### ISSUE TITLE
App crashes when add button is pressed without selecting any image

### ISSUE THREAD

**Issue by laibashakir** [itxtalal/react-gallery#1]
When using the React Gallery App, there is a problem where the application crashes when the "Add" button is pressed without selecting any image. This issue occurs when attempting to add an image to the gallery without first choosing a file. The app should handle this scenario gracefully and provide a user-friendly error message or prevent the crash from occurring altogether.

## Potential Fixes

1. Error Handling

**Comment by laibashakir** [comment]
### File AddImageModal.jsx

1. In the PreviewImage function, we need to ensure that we return the preview of an image only if a file is uploaded. This means checking if the uploaded file is present before generating the preview.
2. In the FileUpload function, we should perform actions on file-related states only if the user selects a file. This means checking if a file is selected before proceeding with any file-related operations.

### File ImagesCtx.jsx

1. In the addImage function, we should avoid updating the context states if no image is uploaded by the user or if the user cancels the upload by closing the modal or pressing the add button without selecting a file. This means checking if an image is uploaded before updating the context states.

Please review the mentioned files and make the necessary modifications as described above.
![issue](https://github.com/itxtalal/react-gallery/assets/65224815/34d26b5e-08bd-434d-9ef7-2a549416c5b4)
![issue 1](https://github.com/itxtalal/react-gallery/assets/65224815/16e71b1d-22fd-494a-bbce-2eee5b518082)

**Comment by itxtalal** [comment]
Issue fixed -> https://github.com/itxtalal/react-gallery/pull/2
